-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", file.BOARD_ID, "/", file.FILE_ID, file.FILE_NAME, file.FILE_EXT) as FILE_PATH
FROM USED_GOODS_FILE as file LEFT JOIN USED_GOODS_BOARD as board ON file.BOARD_ID = board.BOARD_ID
WHERE board.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY file.FILE_ID desc
