-- 코드를 입력하세요
SELECT B.BOOK_ID as BOOK_ID, A.AUTHOR_NAME as AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK as B join AUTHOR as A WHERE B.AUTHOR_ID = A.AUTHOR_ID and B.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE asc